
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s.io.config
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- name: dev.cloudnativetoolkit.klustered
  namespaceSelector:
    matchExpressions:
    - key: klustered
      operator: In
      values:
      - v2
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    url: https://klustered.dlze6x7tnnz.eu-gb.codeengine.appdomain.cloud
#    service:
#      namespace: default
#      name: klustered
#      path: "/"
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 30
  #failurePolicy: Ignore