
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s.io.config
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- name: dev.cloudnativetoolkit.klustered-validating
  rules:
  - apiGroups:   ["admissionregistration.k8s.io"]
    apiVersions: ["v1"]
    operations:  ["DELETE"]
    resources:   ["mutatingwebhookconfigurations"]
    scope:       "Cluster"
  clientConfig:
#    url: https://mutating.dlze6x7tnnz.eu-gb.codeengine.appdomain.cloud
    service:
      namespace: default
      name: klustered-validating
      path: "/"
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 30